apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  source:
    repoURL: https://github.com/westelh/personal-k8s-clusters.git
    # Path needs to be overridden in overlays
    path: change-me
    targetRevision: master
