apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt 
spec:
  project: default
  source:
    chart: lencr
    repoURL: https://westelh.github.io/helm-charts
    targetRevision: 0.0.1
    helm: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd