apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: ^0.27.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
