apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-consul-server
  namespace: default
  labels:
    release: {{ .Release.Name }}
spec:
  endpoints:
  - path: /v1/agent/metrics
    port: https
    scheme: https
    scrapeTimeout: 30s
    tlsConfig:
      ca:
        secret:
          name: consul-vault-ca
          key: vault.ca
      serverName: consul-server
  jobLabel: monitoring
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: consul
      component: server
