apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: default
  annotations: {{ toYaml .Values.monitoring.prometheus.ingress.annotations | nindent 3 }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.monitoring.prometheus.ingress.dnsName }}
      secretName: prometheus-tls
  rules:
  - host: {{ .Values.monitoring.prometheus.ingress.dnsName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-kube-prometheus-prometheus
            port:
              number: 9090