apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-root
  namespace: default
spec:
  isCA: true
  commonName: monitoring-root
  secretName: {{ .Values.certManager.ca.root.secretName}}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.certManager.issuer.name }}
    kind: Issuer
    group: cert-manager.io