repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: cert-manager
  url: https://charts.jetstack.io
- name: external-secrets
  url: https://charts.external-secrets.io
- name: hashicorp
  url: https://helm.releases.hashicorp.com

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: ~4.7.2
- name: cert-manager
  namespace: cert-manager
  version: ^1.13.0
  chart: cert-manager/cert-manager
  values:
  - installCRDs: true
- name: external-secrets
  namespace: external-secrets
  chart: external-secrets/external-secrets
  values:
  - installCRDs: true
- name: vault
  namespace: vault
  chart: hashicorp/vault