repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: cert-manager
  url: https://charts.jetstack.io

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: ~4.7.2
- name: cert-manager
  namespace: cert-manager
  version: ^1.13.0
  chart: cert-manager/cert-manager
