apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/westelh/personal-k8s-clusters.git
      revision: HEAD
      directories:
      - path: infra/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        chart: '{{.path.basename}}'
        repoURL: https://github.com/westelh/personal-k8s-clusters.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          releaseName: '{{.path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        syncOptions:
        - CreateNamespace=true