apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.5
    helm:
      releaseName: external-secrets
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: external-secret
