apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: trust-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v0.6.0
    helm:
      releaseName: trust-manager
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager