apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.25.0
    helm:
      releaseName: vault
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
