monitoring:
  grafana:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: localhost
      dnsName: localhost
  prometheus:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: localhost
      dnsName: localhost

kube-prometheus-stack:
  grafana:
    serviceMonitor:
      labels:
        release: {{ .Release.Name }}
  nodeExporter:
    enabled: false

metrics-server:
  args:
  - --kubelet-insecure-tls
