monitoring:
  grafana:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: grafana.kestrel.westelh.dev
      dnsName: grafana.kestrel.westelh.dev
  prometheus:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: grafana.kestrel.westelh.dev
      dnsName: prometheus.kestrel.westelh.dev

kube-prometheus-stack:
  grafana:
    serviceMonitor:
      labels:
        release: {{ .Release.Name }}
  nodeExporter:
    enabled: false
  coreDns:
    service:
      selector:
        k8s-app: coredns
  kubeEtcd:
    enabled: false
  kubeScheduler:
    service:
      selector:
        k8s-app: kube-scheduler
  kubeControllerManager:
    service:
      selector:
        k8s-app: kube-controller-manager

metrics-server:
  args:
  - --kubelet-insecure-tls
