apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    chart: consul
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.3.0
    helm:
      valuesObject:
        global:
          datacenter: lark
  destination:
    server: "https://kubernetes.default.svc"
    namespace: consul
