apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
spec:
  project: default
  source:
    chart: consul
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.3.0
    helm:
      valuesObject:
        global:
          name: consul
          datacenter: lark
          secretsBackend:
            vault:
              enabled: true
              consulServerRole: consul-server
              consulClientRole: consul-client
              connectCA:
                address: http://vault.default.svc.cluster.local:8200
                authMethodPath: kubernetes
                rootPKIPath: pki
                intermediatePKIPath: pki_int1
          gossipEncryption:
            secretName: kv/data/consul/gossip
            secretKey: key
          tls:
            enabled: true
            enableAutoEncrypt: true
            caCert:
              secretName: pki/cert/ca
        server:
          serverCert:
            secretName: pki_int1/issue/consul-server

  destination:
    server: "https://kubernetes.default.svc"
    namespace: consul

