apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
spec:
  project: default
  source:
    chart: consul
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.3.0
    helm:
      valueFiles:
      - "applications/consul-values.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
