apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
spec:
  project: default
  source:
    chart: consul
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.3.0
    helm:
      valuesObject:
        global:
          name: consul
          datacenter: lark
          secretsBackend:
            vault:
              enabled: true
              consulServerRole: consul-server
              consulClientRole: consul-client
              connectInjectRole: consul-connect-injector
              consulCARole: consul-ca
              connectCA:
                address: http://vault.default.svc.cluster.local:8200
                authMethodPath: kubernetes
                rootPKIPath: pki
                intermediatePKIPath: consul-ca
              connectInject:
                tlsCert:
                  secretName: pki/issue/connectInjector
                caCert:
                  secretName: pki/cert/ca
          gossipEncryption:
            secretName: kv/data/consul/gossip
            secretKey: key
          tls:
            enabled: true
            enableAutoEncrypt: true
            caCert:
              secretName: pki/cert/ca
          federation:
            enabled: true
            createFederationSecret: true
        server:
          replicas: 3
          serverCert:
            secretName: pki/issue/consul-server
        syncCatalog:
          enabled: true
        meshGateway:
          enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: consul

