apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt 
spec:
  project: default
  source:
    chart: lencr
    repoURL: https://westelh.github.io/helm-charts
    targetRevision: 0.0.2
    helm:
      valuesObject:
        lencr:
          endpoint:
            url: https://acme-v02.api.letsencrypt.org/directory

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd