apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack 
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.9.11
    helm:
      valuesObject: []
    server: "https://kubernetes.default.svc"
    namespace: default
