apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack 
  annotations:
    avp.kubernetes.io/path: "kv/data/loki/s3"
spec:
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.9.11
    helm:
      valuesObject:
        loki:
          storage:
            type: s3
            s3:
              endpoint: nrenghdficwo.compat.objectstorage.ap-tokyo-1.oci.customer-oci.com
              secretAccessKey: <key>
              accessKeyId: <id>
            bucketNames:
              chunks: lark-loki-chunks-8acffb9b89ee2a09
              ruler: lark-loki-ruler-5384c69d576fd544
              admin: lark-loki-admin-5c49dfca26dedf33
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
