apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack 
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd/loki"
spec:
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.9.11
    helm:
      valuesObject:
        loki:
          loki:
            storage:
              type: s3
              s3:
                endpoint: <endpoint>
                secretAccessKey: <key>
                accessKeyId: <id>
              bucketNames:
                chunks: <chunks>
                ruler: <ruler>
                admin: <admin>
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
