apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd/loki"
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.41.4
    helm:
      valuesObject:
        loki:
          storage:
            type: s3
            s3:
              secretAccessKey: <key>
              accessKeyId: <id>
              region: ap-tokyo-1
              http_config:
                insecure_skip_verify: true
              endpoint: <endpoint>
              s3forcepathstyle: true
            bucketNames:
              chunks: <chunks>
              ruler: <ruler>
              admin: <admin>
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
