apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 54.2.2
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            serviceMonitorSelector:
              matchLabels:
                release: kube-prometheus-stack
                monitoring: kube-prometheus-stack
        grafana:
          persistence:
            enabled: true
            type: pvc
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: lencr-issuer
            hosts:
              - grafana.westelh.dev
            tls:
              - hosts:
                  - grafana.westelh.dev
                secretName: grafana-tls
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
