apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: ^0.27.0
    helm:
      releaseName: vault
      valuesObject:
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            tls:
            - hosts:
              - vault.westelh.dev
              secretName: vault-tls
            hosts:
            - host: vault.westelh.dev
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: vault
                      port:
                        number: 8200
            annotations:
              cert-manager.io/issuer: lencr-issuer
              cert-manager.io/issuer-kind: ClusterIssuer
              cert-manager.io/common-name: vault.westelh.dev

  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
