apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  source:
    helm:
      valuesObject:
        server:
          ingress:
            ingressClassName: nginx
            tls:
            - hosts:
              - vault.westelh.dev
              - localhost
              - 127.0.0.1
              secretName: vault-tls
            annotations:
              cert-manager.io/issuer: step-issuer
              cert-manager.io/common-name: vault
              cert-manager.io/issuer-kind: StepIssuer
              cert-manager.io/issuer-group: certmanager.step.sm
