apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.10.0
- cmp-plugin.yaml
- rbac.yaml
- certificates.yaml
- ingress.yaml

patches:
- path: argocd-repo-server-deploy.yaml
- path: argocd-cm.yaml
