---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-repo-server
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["argocd-vault-plugin-credentials"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-repo-server
subjects:
- kind: ServiceAccount
  name: argocd-repo-server
roleRef:
  kind: Role
  name: argocd-repo-server
  apiGroup: rbac.authorization.k8s.io
