apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
    helm:
      releaseName: nfs-subdir-external-provisioner
      valuesObject:
        nfs:
          server: {{ .Values.server }}
          path: {{ .Values.path }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default