apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-controller
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.7.2
    helm:
      releaseName: ingress-nginx
      valuesObject:
        controller:
          extraArgs:
            enable-ssl-passthrough: "true"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx
