environments:
  dev:
    values:
    - ../environments/dev/values.yaml
  kestrel:
    values:
    - ../environments/kestrel/values.yaml
  lark:
    values:
    - ../environments/bakke/values.yaml
---
repositories:
- name: nfs-subdir-external-provisioner
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
releases:
- name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
  chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
  version: ~4.0.18
  condition: baremetal.enabled
  values:
  - {{ .Values.nfsSubdirExternalProvisioner | toYaml | nindent 4 }}

- name: loadbalancer
  namespace: metallb
  chart: ./loadbalancer
  condition: baremetal.enabled
  values:
  - {{ .Values.loadbalancer | toYaml | nindent 4 }}
