baremetal:
  enabled: true

nfsSubdirExternalProvisioner:
  nfs:
    server: 172.20.200.1
    path: /pv

loadbalancer:
  iPAddressPool:
    addresses:
    - 172.20.100.1-172.20.100.255

ingressNginx:
  controller:
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 172.20.100.1

vaultSecretsOperator: {}

grafanaOperator: {}
