environments:
  default:
    values:
    - ../environments/default/values.yaml
  kestrel:
    values:
    - ../environments/kestrel/values.yaml
---
repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: cert-manager
  url: https://charts.jetstack.io

releases:
- name: metallb
  namespace: metallb
  chart: metallb/metallb
  condition: baremetal.enabled
  version: ~0.13.11

- name: cert-manager
  namespace: cert-manager
  version: ^1.13.0
  chart: cert-manager/cert-manager
  values:
  - installCRDs: true

- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: ~4.7.2
  values:
  - controller:
      extraArgs:
        enable-ssl-passthrough: "true"
