resources:
- "../../base"

buildMetadata: [managedByLabel, originAnnotations]

patches:
- path: add-vault-ingress-notation.patch.yaml
- path: add-vault-ingress-host.patch.yaml
  target:
    kind: Application
    name: vault
    namespace: vault
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argocd
      namespace: argocd
    spec:
      source:
        path: "apps/argocd/overlays/dev"
- path: add-monitoring-values.patch.yaml
  target:
    kind: Application
    name: monitoring
    namespace: monitoring
- path: add-sd-helm-values.patch.yaml
  target:
    kind: Application
    name: service-discovery
    namespace: default