resources:
- "../../base"

buildMetadata: [managedByLabel, originAnnotations]

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argocd
    spec:
      source:
        path: "apps/argocd/overlays/dev"
- path: add-monitoring-values.patch.yaml
  target:
    kind: Application
    name: monitoring
- path: add-sd-helm-values.patch.yaml
  target:
    kind: Application
    name: service-discovery

- path: add-vault-integration-values-path.yaml
  target:
    kind: Application
    name: vault-integration