apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: vault
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: ^0.27.0
    helm:
      releaseName: vault
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
