spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/westelh/personal-k8s-clusters
    targetRevision: HEAD

ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: "true"
